"""Build marbles.html — a fully self-contained copy of index.html.

index.html is the hosted PWA (needs manifest.webmanifest, icons, sw.js next to it).
marbles.html needs nothing else: icon inlined as a data URI, no manifest / service
worker. Open it straight from disk, email it, or drop it anywhere.

    python3 build_standalone.py
"""
import base64
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent
src = (ROOT / "index.html").read_text(encoding="utf-8")
icon = "data:image/png;base64," + base64.b64encode((ROOT / "icon-192.png").read_bytes()).decode()

replacements = {
    '<link rel="manifest" href="manifest.webmanifest">\n': "",
    '<link rel="icon" type="image/png" sizes="512x512" href="icon-512.png">':
        f'<link rel="icon" type="image/png" href="{icon}">',
    '<link rel="apple-touch-icon" href="icon-192.png">':
        f'<link rel="apple-touch-icon" href="{icon}">',
    "navigator.serviceWorker.register('sw.js')": "Promise.reject()",   # no sidecar sw.js in standalone mode
}
out = src
for old, new in replacements.items():
    if old not in out:
        raise SystemExit(f"build_standalone: expected snippet not found: {old[:60]!r}")
    out = out.replace(old, new)
out = out.replace("<title>Marbles</title>", "<title>Marbles</title>\n<!-- GENERATED by build_standalone.py from index.html. Edit index.html, not this file. -->", 1)

(ROOT / "marbles.html").write_text(out, encoding="utf-8")
print(f"marbles.html written ({len(out)//1024} KB, self-contained)")
